version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-finance
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - finance-net

volumes:
  redis_data:

networks:
  finance-net:
    driver: bridge
